name: Bug report
description: Submit a bug report
title: "[BUG] <Title>"
labels: [bug]
body:
- type: markdown
  attributes:
    value: "Welcome to `neuromaps`! Please fill out the following information describing the bug you have encountered."
- type: textarea
  id: summary
  attributes:
    label: Issue summary
    description: "Please provide a brief, 1-2 sentence overview of the issue."
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Detailed issue description
    description: "If more information is needed to describe your issue, please provide that here."
- type: textarea
  id: reproduction
  attributes:
    label: Steps to reproduce issue
    description: "Please describe steps that can be taken to reproduce your issue."
    value: |
      >>>
      >>>
      >>>
      ...
    render: python
  validations:
    required: true
- type: input
  id: version
  attributes:
    label: Software version
    description: "What version of `neuromaps` are you using? (If you are unsure you can run `python -c 'import neuromaps; print(neuromaps.__version__)'`"
- type: checkboxes
  id: os
  attributes:
    label: "What operating system were you using when you encountered this issue?"
    options:
      - label: macOS
      - label: Windows
      - label: Linux
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: "By submitting this issue you agree to follow our [Code of Conduct](https://github.com/netneurolab/.github/blob/27712b33f41373c35206e3a87700a340aee18ac5/CODE_OF_CONDUCT.md)."
    options:
      - label: I agree to follow the `neuromaps` Code of Conduct
        required: true
