name: Issue template
description: Submit an issue
title: " "
body:
- type: markdown
  attributes:
    value: "Welcome to `neuromaps`! Please fill out the following information."
- type: textarea:
  id: description
  attributes:
    label: Description of issue
    description: "Please use this space to describe the issue using as much detail as needed."
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: "By submitting this issue you agree to follow our [Code of Conduct](https://github.com/netneurolab/.github/blob/27712b33f41373c35206e3a87700a340aee18ac5/CODE_OF_CONDUCT.md)."
    options:
      - label: I agree to follow the `neuromaps` Code of Conduct
        required: true
