name: deploy-docs

on:
  push:
    branches:
    - main
    paths:
    - docs/**
    - examples/**

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -r docs/requirements.txt
        wget https://www.humanconnectome.org/storage/app/media/workbench/workbench-linux64-v1.5.0.zip
        unzip workbench-linux64-v1.5.0.zip -d ${HOME}
        echo "$HOME/workbench/bin_linux64" >> $GITHUB_PATH

    - name: Install brainnotation
      run: |
        pip install ./

    - name: Build the book
      run: |
        cd docs && make clean html

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        commit_message: ${{ github.event.head_commit.message }}
